version: '3.8'
services:
  # Container para o backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: amarassist-backend
    container_name: amarassist-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - amarassist-vendor:/var/www/vendor
      - ./backend/storage/app/public:/var/www/storage/app/public
    networks:
      - amarassist-network
    depends_on:
      - db

  # Container para o MySQL
  db:
    image: mysql:8.0
    container_name: amarassist-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: amarassist
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - amarassist-network
      
  # Container para o front-end Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: amarassist-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - amarassist-network

volumes:
  db-data:
  amarassist-vendor:


networks:
  amarassist-network:
    driver: bridge
